// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bcbrpidusatbrrugdbco.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJjYnJwaWR1c2F0YnJydWdkYmNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NzI0NDksImV4cCI6MjA2NTE0ODQ0OX0.uIAKr6hL5CNdYXRsiUKB6ciyVAkNqso19w_KUKkKHrE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);